services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: jobtrak-postgres
    environment:
      POSTGRES_DB: jobtrak
      POSTGRES_USER: jobtrak_user
      POSTGRES_PASSWORD: jobtrak_secure_password_2024
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"  # Expose for external access if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - jobtrak-data-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobtrak_user -d jobtrak"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_connections=100
      -c log_min_duration_statement=1000

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: jobtrak-redis
    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendfsync everysec
      --tcp-keepalive 300
      --timeout 300
    ports:
      - "6379:6379"  # Expose for external access if needed
    volumes:
      - redis_data:/data
    networks:
      - jobtrak-data-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  jobtrak-data-network:
    external: true  # This should be external: true
    name: jobtrak-data-network

volumes:
  postgres_data:
    driver: local
    name: jobtrak-postgres-data
  redis_data:
    driver: local
    name: jobtrak-redis-data
