# Promtail configuration for JobTrak log collection
# File: logging/promtail-config.yml

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Application logs from mounted volume
  - job_name: jobtrak-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: jobtrak-application
          __path__: /var/log/jobtrak/*.log
    pipeline_stages:
      - match:
          selector: '{job="jobtrak-application"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<message>.*)'
            - labels:
                level:
            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05'

  # API access logs
  - job_name: jobtrak-access-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: jobtrak-access
          __path__: /var/log/jobtrak/access.log
    pipeline_stages:
      - json:
          expressions:
            method: method
            status: status
            path: path
            response_time: response_time
      - labels:
          method:
          status:

  # Error logs
  - job_name: jobtrak-error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: jobtrak-errors
          level: error
          __path__: /var/log/jobtrak/error.log

  # Docker container logs
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/jobtrak-(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_name']
        regex: '/jobtrak-(.*)'
        target_label: 'job'
        replacement: 'jobtrak-${1}'
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{job=~"jobtrak-.*"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z) (?P<message>.*)'
            - labels:
                container:
            - timestamp:
                source: timestamp
                format: RFC3339Nano

  # Job processing logs (if you have specific job log files)
  - job_name: jobtrak-jobs
    static_configs:
      - targets:
          - localhost
        labels:
          job: jobtrak-jobs
          __path__: /var/log/jobtrak/jobs/*.log
    pipeline_stages:
      - match:
          selector: '{job="jobtrak-jobs"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] Job: (?P<job_id>\w+) - (?P<message>.*)'
            - labels:
                level:
                job_id: