# API Configuration
api:
  level: INFO
  host: 0.0.0.0
  port: 8000

# Database Configuration
database:
  path: postgresql://postgres:postgres@infra-postgres:5432/postgres

# Model Configuration
model:
  provider: openai
  name: gpt-4.1-mini
  temperature: 0.3

# Project Paths
paths:
files:
  prompts_yaml: prompts/prompts.yaml
  descriptions_yaml: prompts/extractor_descriptions.yaml

# Application Settings
settings:
  max_concurrent_workers: 4
  max_retries: 3
  backoff_factor: 5
